{
 "title": "Bot_Detector Updates",
 "description": "Bot Detector Dashboard",
 "time": { "from": "2026-05-01T04:00:00.000Z", "to": "2026-05-31T03:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "url",
    "label": "Url",
    "query": {
     "query": "from(bucket: \"Bot-Detector-Bucket\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"url\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This section provides a high-level overview of website activity through a series of summary panels displaying both total counts and activity rates for key metrics. Panels for Site Views, Hits, Bot Hits, and Crons allow users to quickly assess overall traffic patterns, automated crawler activity, and scheduled task execution. By presenting both cumulative totals and current rates, the dashboard helps identify trends, monitor system performance, and detect unusual spikes or changes in activity at a glance."
   }
  },
  {
   "title": "Site Views",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\n  |> filter(fn: (r) => r[\"_value\"] == \"/\")\n  |> map(fn: (r) => ({ r with _field: \"url_total\" }))\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\n  |> yield(name: \"url_total\")\n"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\n  |> map(fn: (r) => ({ r with _field: \"url_total\" }))\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\n  |> yield(name: \"url_total\")"
    }
   ]
  },
  {
   "title": "Bot Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"is_bot\")\n  |> filter(fn: (r) => r[\"_value\"] == true)\n  |> map(fn: (r) => ({ r with _field: \"bot_total\" }))\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\n  |> yield(name: \"bot_total\")\n"
    }
   ]
  },
  {
   "title": "Crons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"BOT-DETECTOR-BUCKET\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\n  |> filter(fn: (r) => strings.containsStr(v: r._value, substr: \"/wp-cron.php\"))\n  |> map(fn: (r) => ({ r with _field: \"query_A\" }))\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\n  |> yield(name: \"query_A\")\n"
    }
   ]
  },
  {
   "title": "General",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "This dashboard section provides deeper insight into website traffic patterns and visitor behavior. The Hits by IP Address panel highlights the most active IP addresses generating requests, helping identify high-volume users, services, or potential sources of unusual activity. The Status Codes panel summarizes server responses, allowing administrators to quickly monitor successful requests, redirects, client errors, and server errors. The % Bots panel displays the proportion of traffic attributed to automated crawlers and bots, offering visibility into how much of the site's activity comes from non-human visitors. Complementing this, the Calendar Hits by Bots panel visualizes bot activity over time, making it easy to identify trends, spikes, and recurring patterns in automated traffic across specific days and periods."
   }
  },
  {
   "title": "Hits by IP Address",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"ip_address\"])"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"status_code\")\n"
    }
   ]
  },
  {
   "title": "% Bots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"is_bot\")\n"
    }
   ]
  },
  {
   "title": "Calendar Hits by Bots",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"is_bot\", \"url\"])"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "This section provides detailed insight into site hit activity and traffic characteristics. A hit represents any request made to the site, regardless of the specific URL or resource being accessed. Because a single page view or site visit often requires multiple requests—for example, to load images, stylesheets, scripts, or third-party integrations—there is typically a many-to-one relationship between hits and site visits. The Hits - Total panel displays the overall volume of requests received, while Hits - By User Agent breaks down traffic by browser, crawler, application, or device type. The Hits - By User Agent Trend panel shows how traffic from different user agents changes over time, helping identify shifts in user behavior or automated activity. Finally, the Response Size panel measures the amount of data returned by the site, providing insight into bandwidth consumption and content delivery patterns."
   }
  },
  {
   "title": "Hits - Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"user_agent\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\"])"
    }
   ]
  },
  {
   "title": "Hits - By User Agent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"user_agent\")"
    }
   ]
  },
  {
   "title": "Hits - By User Agent Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"user_agent\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\"])"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"response_size\"])"
    }
   ]
  },
  {
   "title": "Hits by URL",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "This section contains panels that provide insight into activity for specific URLs on the site. The Hits by URL panel identifies which pages, endpoints, or resources are receiving the most requests, while the Hits by URL – Trend panel shows how request volumes change over time. Together, these panels help administrators detect unusual spikes in traffic, identify heavily accessed resources, and investigate potential issues caused by automated processes, plugins, bots, or misconfigured applications that may be generating excessive URL invocations. Monitoring URL-level activity can also assist with performance tuning, capacity planning, and troubleshooting unexpected site behavior."
   }
  },
  {
   "title": "Hits by URL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\",  \"url\"])"
    }
   ]
  },
  {
   "title": "Hits by URL - Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"regexp\"\nsafeValue = regexp.quoteMeta(v: \"${url}\")\nv_regex = regexp.compile(v: safeValue)\n\nfrom(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"url\")\n    //|> filter(fn: (r) => contains(value: r[\"_value\"], set: ${url:json}))\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"url\"])"
    }
   ]
  },
  {
   "title": "Site Views",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 91 },
   "options": {
    "content": "This section contains panels that provide insight into site view activity and visitor behavior. The Site Views - Trend panel shows how site views change over time, helping identify traffic patterns, growth, and unusual spikes in activity. The Site Views - By User Agent panel breaks down site views by browser, application, or device type, allowing administrators to understand how visitors are accessing the site. The Site Views - By IP Address panel highlights the sources of site traffic by IP address, making it easier to identify high-volume visitors, troubleshoot access issues, and detect potentially abnormal or suspicious activity."
   }
  },
  {
   "title": "Site Views - Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\" and r._field == \"url\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"url\"])"
    }
   ]
  },
  {
   "title": "Site Views - By User Agent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"url\"])\n   "
    }
   ]
  },
  {
   "title": "Site Views by IP Address",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"url\", \"ip_address\"])"
    }
   ]
  },
  {
   "title": "Bots",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 120 },
   "options": {
    "content": "This section contains panels with information about bot traffic. There is an indicator in the http_access_log entry that specifies whether a request was generated by a bot. These panels provide visibility into the volume of bot-generated hits, trends in bot activity over time, and the amount of response data transferred to bots. This information is useful for identifying search engine crawlers, monitoring automated traffic patterns, detecting unusual bot behavior, and understanding the impact of bot activity on site resources and bandwidth consumption."
   }
  },
  {
   "title": "Hits by Bots",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"is_bot\"])"
    }
   ]
  },
  {
   "title": "Hits by Bots - Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"is_bot\"])"
    }
   ]
  },
  {
   "title": "Response Size by Bot",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BOT-DETECTOR-BUCKET\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"http_access_log\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> keep(columns: [\"_time\", \"user_agent\", \"is_bot\", \"response_size\"])"
    }
   ]
  }
 ]
}